### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by melaniepriscila** [CreemosEnLaRed/entregas#10]
Dirección de la actividad: melaniepriscila.github.io/actividad1

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó poder enlazar a otras páginas, para agregar redes sociales etc y también cambiarle el nombre para que se vea más profesional.

...

**Que no fue claro de la actividad?**
Estuvo muy clara.

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Hola Melanie! Que bueno que volviste al taller. Esta bien tu actividad, aprobada!

Como comentario fijate que en pagina.html tenes un enlace roto porque estas usando la ruta relativa` img/rainbow.png` pero no tenes un directorio llamado `/img/` dentro de tu directorio `/actividad1/`. Para que ande deberias crear un dir llamado img y pegar la imagen rainbow ahi.

De todos modos se nota que lo entendiste porque en el index usas bien la ruta relativa para el unicornio, asi que todo piola. Abrazo.
