### ISSUE TITLE
Entrega de Actividad 3 - clara-reyna

### ISSUE THREAD

**Issue by clara-reyna** [CreemosEnLaRed/entregas#100]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://clara-reyna.github.io/Actividad-3

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Todo!!! :smile: quiero más jajaja

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
casi perfecto :rofl: (fijate que el archivo lo nombraste intex.html :) aprobada igual!
