### ISSUE TITLE
Entrega de Actividad 3 - <Ro 📻>

### ISSUE THREAD

**Issue by ro-mana** [CreemosEnLaRed/entregas#101]
Dirección de la actividad: https://ro-mana.github.io/actividad-3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó que  ya comenzaramos a tocar código html y me costó bastante, por eso creo que está bien que hayamos empezado ahora y no antes. Comencé a editar en Chrome y luego me tuve que pasar a Firefox porque si no no se veían los íconos de usuario y contraseña, no sé por qué será.

**Que no fue claro de la actividad?**
Hasta los últimos 10 minutos creí  que no entendía nada y después cuando tuve que ver qué había hecho mal, recién ahí empecé a entender(me) un poco. Pero creo que es cuestión de ensayo y error de cada uno. Por ahí lo que no entiendo mucho son los divs porque no encuentro una analogía en la gramática de humanxs jaja

**Como podríamos mejorarla?**
A lo mejor serviría recomendar algún  "glosario" con los nombres de los tags, que creo que Mariano nombró en un video.

**Comment by marianoguerra** [comment]
hay unos detalles a corregir, fijate que donde escribiste `<div class="input-group-text" <span class="input-group-prepend">👨🏽‍🦱</span>` te falta el `>` despues de `"input-group-text"`

lo mismo te paso en el icono de la llave.

en `<input class type="password" class="form-control mt-3"` tenes class escrito dos veces, aunque no es un gran problema, solo lo senialo para que lo notes :)

**Comment by ro-mana** [comment]
Revisado! Gracias!!

**Comment by marianoguerra** [comment]
aprobado!
