### ISSUE TITLE
Entrega de Actividad 3 - <@vanetel>

### ISSUE THREAD

**Issue by vanpini** [CreemosEnLaRed/entregas#102]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://vanpini.github.io/actividad-3

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
terminar un ejercicio completo...y en el medio ir aprendiendo cosas
...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
* tenes dos veces un tag `<imput>` (nota la m)
* `<button class="btn-primary w-100">Login</button>` le falta la clase `btn`
* `<div clas="input-group-prepend">` fijate que es `class` en lugar de `clas` (te paso en dos lugares)

cuando corrijas eso avisa y te aprobamos :)

**Comment by marianoguerra** [comment]
aprobado!
