### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by josuelaa** [CreemosEnLaRed/entregas#103]
Dirección de la actividad: https://josuelaa.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me gusta que hacen videos tutoriales super claros para todo! Mil gracias por el curso, es excelente

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Perfecto!
