### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by desileonardi** [CreemosEnLaRed/entregas#106]
Dirección de la actividad: https://desileonardi.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Muy bueno que hayas probado con los tags y las clases!
