### ISSUE TITLE
Entrega de Actividad 3 - LUCIANA

### ISSUE THREAD

**Issue by lucianaprogramadora** [CreemosEnLaRed/entregas#107]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://lucianaprogramadora.github.io/actividad3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
TODO..

**Que no fue claro de la actividad?**

...si escribiendo es necesario hacer espacios o no y porque a veces en vez de salir despues de escribir < sale en rojo y no en bordo 

**Como podríamos mejorarla?**
me costo seguir el video y escribir el dictado pero iba viendo la actividad en el celu y ahi me iba mejor 
...

**Comment by marianoguerra** [comment]
en `<input type="password" class="form-control mt-3"placeholder=Password>` te falto un espacio antes de `placeholder` y las comillas en `Password`

en `<input type="text"class= "form-control" placeholder="Username">` te falto espacio antes de `class`.

si queres/podes corregilos, pero estas aprobada igual :smile_cat:

**Comment by lucianaprogramadora** [comment]
MORTALL SII LO VOY A INTENTAR CORREGIR !SALUDOS
