### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by Flor93** [CreemosEnLaRed/entregas#109]
Dirección de la actividad: https://flor93.github.io/actividad-2/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Sí, me encanto la actividad. La verdad que venía postergandola justamente para hacerla con tiempo y me gusto. 
...

**Que no fue claro de la actividad?**
Muy clara la actividad

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Perfecto!
