### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by juliaporto** [CreemosEnLaRed/entregas#11]
Dirección de la actividad: https://juliaporto.github.io/actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustan las actividades porque son super concretas y se va viendo hacia dónde nos llevan. Personalmente no conocía ninguna de las herramientas que nos están facilitando, ni bloques web ni github.

...

**Que no fue claro de la actividad?**

**Como podríamos mejorarla?**

Sugiero la posibilidad de trazar un pequeño plan antes de grabar los videos... Para que el desarrollo de los contenidos sea más lineal
...

**Comment by lara-garbero-tais** [comment]
Todo en orden, aprobada!
