### ISSUE TITLE
Entrega de Actividad 3 - <Florencia Reynoso>

### ISSUE THREAD

**Issue by Flor93** [CreemosEnLaRed/entregas#111]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://flor93.github.io/actividad-3/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
fijate en `<input type="text" class="form-control"placeholder="Username">` te falto el espacio antes de `placeholder` y en `<input type"password"` te falto el `=` despues de `type`.

si queres/podes corregilo, pero esta aprobado igual :lotus_position:

**Comment by Flor93** [comment]
Gracias! si si lo voy a corregir
