### ISSUE TITLE
Entrega de Actividad 3 - <Sele Gomez>

### ISSUE THREAD

**Issue by seleneagomez** [CreemosEnLaRed/entregas#114]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://seleneagomez.github.io/actividad3

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
fijate que en `<input type="text"class` te falto el espacio antes de `class`
y cerraste un div de mas antes de "wrong user or password"

si queres/podes corregilo pero esta aprobado igual :female_detective:
