### ISSUE TITLE
Entrega de Actividad 3 - <Trinidad>

### ISSUE THREAD

**Issue by trinidadtomasini** [CreemosEnLaRed/entregas#116]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://trinidadtomasini.github.io/actividad-3/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me encanta el ritmo de Mariano para dar las actividades, se me hacen entretenidas y no pesadas. Me pareció que la cantidad de código a escribir estuve perfecta para ser la primera vez.

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?*

Abrí en una ventana el video y en otra la página para escribir el código y dividí la pantalla para poder trabajar con las dos ventanas. Pero igual fue bastante engorroso poder copiar el código y ver bien el video (no sé si me explico bien) Quizá pensar alguna herramienta para esto en caso de ser posible. Abrazo!

**Comment by marianoguerra** [comment]
perfecto! :1st_place_medal:
