### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by RominaSo** [CreemosEnLaRed/entregas#12]
Dirección de la actividad: https://rominaso.github.io/actividad1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Comprender el uso/significado del html, y aprender también a modificarlo sin necesidad de ir a bloques web.

**Que no fue claro de la actividad?**

No tuve dificultades para comprender la actividad. Por el contrario los videos son muy detallados.

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden, actividad aprobada!

**Comment by RominaSo** [comment]
Gracias!!
