### ISSUE TITLE
Entrega de Actividad 3 - <@melaniepriscila>

### ISSUE THREAD

**Issue by melaniepriscila** [CreemosEnLaRed/entregas#121]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: melaniepriscila.github.io/actividad3

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**
La forma de entrega, no sabía si copiar y pegar el código o si se descargaba de algún lado. Sino todo genial como siempre jaja
...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
aprobado!
