### ISSUE TITLE
Entrega de Actividad 4 - <vanetel>

### ISSUE THREAD

**Issue by vanpini** [CreemosEnLaRed/entregas#123]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://vanpini.github.io/actividad4/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

todo

**Que no fue claro de la actividad?**

clarisimo

**Como podríamos mejorarla?**

me gustaria entender como buscar en boostrap las clases que hay y saber que hace cada una

**Comment by marianoguerra** [comment]
aprobado!

si haces click en los links de la izquierda de esta pagina estan todas las clases con ejemplos: https://getbootstrap.com/docs/4.5/getting-started/introduction/
