### ISSUE TITLE
Entrega de Actividad 3 - <Montesdearrabal>

### ISSUE THREAD

**Issue by Montesdearrabal** [CreemosEnLaRed/entregas#129]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://montesdearrabal.github.io/actividad3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
si. muy desafiante.
...

**Que no fue claro de la actividad?**

Todo me gusta! es muy nuevo para mi, esta re bien explicado! 

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
aprobado!
