### ISSUE TITLE
Entrega de Actividad 4 - <Luchi Carioni>

### ISSUE THREAD

**Issue by luchicarioni** [CreemosEnLaRed/entregas#130]
Dirección de la actividad: https://luchicarioni.github.io/actividad-4/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
**Que no fue claro de la actividad?**

No me quedo claro si podiamos cambiar la informacion de la ultima tabla..

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
aprobado!
