### ISSUE TITLE
Entrega de Actividad 4 - clara-reyna

### ISSUE THREAD

**Issue by clara-reyna** [CreemosEnLaRed/entregas#136]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://clara-reyna.github.io/actividad-4

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

El contar con una breve explicacion de CSS, mas un poco de busqueda en google, me permitio avanzar un poco mas, comprender un poco su estructura gral y conocer un poco mas de boostrap, sus clases, etc.  

**Que no fue claro de la actividad?**

**Como podríamos mejorarla?**

Al ir descubriendo y aprendiendo nuevas clases, atributos, etc me doy cuenta que realizo las actividades pero no estoy segura de si mi codigo es "el mas prolijo, optimo, correcto". Se que puede ser muuy dificil pero me gustaria si se pudiesen plantear code review o si en las mismas devoluciones por mail pueden devolvernos como lo hubiesen resuelto ustedes, cosas a mejorar, optimizar, etc ... a mi particularmente me servirian muchisimo sus observaciones o recomendaciones

**Comment by marianoguerra** [comment]
aprobado!
