### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by jeannnegalbo** [CreemosEnLaRed/entregas#14]
Dirección de la actividad: https://jeannnegalbo.github.io/actividad-1/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
La variedad de opciones 
...

**Que no fue claro de la actividad?**
No entendí al principio si tenia que borrar la pagina del ingreso o no.

**Como podríamos mejorarla?**
Quizás pensar en no dar por entendidas algunas cosas, seguramente requiere otros tiempos y energía, pero explicar siempre todo, de todas formas fue super completo. Gracias!
...

**Comment by lara-garbero-tais** [comment]
Bien compa! Actividad aprobada.
