### ISSUE TITLE
Entrega de Actividad 4 - <Ro 📻>

### ISSUE THREAD

**Issue by ro-mana** [CreemosEnLaRed/entregas#144]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://ro-mana.github.io/actividad-4/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
La actividad en sí estuvo muy clara! Les quiero pedir disculpas porque no sé si no me llegó el mail con la actividad o la borré. Por alguna razón pensé que la actividad 4 era practicar en anki. Así que la hice rapidito ahora. La próxima prometo dedicarle más tiempo!!!! 

**Que no fue claro de la actividad?**
...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
aprobado!
