### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by AgoBertax** [CreemosEnLaRed/entregas#15]
Dirección de la actividad: https://agobertax.github.io/actividad1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me gusta que vaya tomando forma de pagina con enlaces y extras.

**Que no fue claro de la actividad?**

se me hizo bardo la mezcla de videos, con el video especifico de enlaces absolutos y relativos.

**Como podríamos mejorarla?**

el ultimo video termino siendo bastante mas util y sencillo, mas facil de comprender. gracias por todo lo que estan haciendo, de verdad es genial!

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
