### ISSUE TITLE
Entrega de Actividad 4 - <Lei Cordoba>

### ISSUE THREAD

**Issue by leicba** [CreemosEnLaRed/entregas#150]
Dirección de la actividad: https://leicba.github.io/actividad-4/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó empezar a entender un poquito de la logica, hasta ahora es la actividad que mas me costo, pero es cuestion de repasar.

**Que no fue claro de la actividad?**
Me costó porque no relacioné el link que había que hacer y no estaba o no lo vi en el video, quizas estaba en otros videos que no vi. Pero a partir de eso pude ver bien las tablas como se iban formando.

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
aprobado!
