### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by ro-mana** [CreemosEnLaRed/entregas#16]
Dirección de la actividad: https://ro-mana.github.io/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me parece interesante que una vez que entendemos cómo funcionan los bloques web tenemos libertad para tocar los códigos de a poquito

**Que no fue claro de la actividad?**

Creo que todo fue claro! Gracias

**Como podríamos mejorarla?**

Por ahora todo está siendo bastante claro y accesible. Estoy segura de que si tuviera más tiempo la podría aprovechar mejor, pero eso ya depende de mí!

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
