### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by cordobake** [CreemosEnLaRed/entregas#17]
Dirección de la actividad: https://cordobake.github.io/Programando/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me gustó que tuve la posibilidad de editar a mi gusto y probar nuevas herramientas y formas.

**Que no fue claro de la actividad?**

Fue muy clara la actividad.

**Como podríamos mejorarla?**

Más actividades para practicar.

**Comment by lara-garbero-tais** [comment]
Clarísimo compa, actividad aprobada!
