### ISSUE TITLE
Entrega de Actividad 4 - <Montesdearrabal>

### ISSUE THREAD

**Issue by Montesdearrabal** [CreemosEnLaRed/entregas#173]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://montesdearrabal.github.io/Actividad4/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me sigue sorprendiendo. Me gusta laexplicación porque siempre es muy clara entonces lo comprendo.
...

**Que no fue claro de la actividad?**
Comprendí todo. Si me queda la duda de como modificar los margenes (como por ejemplo se ve en la página de creemos en la red) en mi caso lo veo completo ocupando en casi toda la página. Seguiré indagando! Gracias!!  
...

**Como podríamos mejorarla?**
Me parece que estan muy bien! yo no se nada y estoy aprendiendo un monton! 
...

**Comment by marianoguerra** [comment]
aprobado!
