### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Remoraland** [CreemosEnLaRed/entregas#18]
Dirección de la actividad: https://remoraland.github.io/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Ir aprendiendo cada vez un poquito mas!
...

**Que no fue claro de la actividad?**
Tal vez ir un poquito mas lento en la demostración de los videos, pero igual supongo que será cuestión de irse familiarizando de a poco (ya nos iremos adaptando).
...

**Como podríamos mejorarla?**
No tengo más que agradecimiento por toda la energía y el tiempo que nos dedican! ---sólo Telegram se satura y no lo leo, pero me dijeron que no pasaba nada si no lo leía! ;)  Ahora con los mails que recibo, ya no necesito Telegram y es mucho mas ordenado para organizarse con lo que hay que hacer. Mil gracias de nuevo por esta oportunidad!!!
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada. Gracias por las cosas lindas que nos decis <3
