### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by casandra22** [CreemosEnLaRed/entregas#19]
Dirección de la actividad: https://casandra22.github.io/actividad1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me encanta seguir aprendiendo.
...

**Que no fue claro de la actividad?**
Entendí todo a través de los videos, excepto el tema de los brunchs que tuve que resolverlo por privado
...

**Como podríamos mejorarla?**
-
...

**Comment by lara-garbero-tais** [comment]
Actividad aprobada. Está muy bien!
