### ISSUE TITLE
Entrega de Actividad 3 - <19k>

### ISSUE THREAD

**Issue by cordobake** [CreemosEnLaRed/entregas#190]
Dirección de la actividad: https://github.com/cordobake/actividad-3

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

La práctica.

**Que no fue claro de la actividad?**

Fue muy clara la explicación y actividad.

**Como podríamos mejorarla?**

Me pareció ideal, no le agregaría mejora.

**Comment by marianoguerra** [comment]
aprobado!
