### ISSUE TITLE
Entrega de Actividad 4 - <19k>

### ISSUE THREAD

**Issue by cordobake** [CreemosEnLaRed/entregas#192]
Dirección de la actividad: https://cordobake.github.io/actividad-4/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

La práctica

**Que no fue claro de la actividad?**

Todo estuvo claro.

**Como podríamos mejorarla?**

Más práctica.

**Comment by marianoguerra** [comment]
aprobado!
