### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by josuelaa** [CreemosEnLaRed/entregas#20]
Dirección de la actividad: https://josuelaa.github.io

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me parece muy útil que haya videitos cortos para cada cosa, así si tengo una duda puntual puedo ir directamente a ese tema. Gracias por todo!!!

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Está muy bien, le pusiste mucha onda! Muchas gracias. Actividad aprobada.
