### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by micha0692** [CreemosEnLaRed/entregas#21]
Dirección de la actividad: https://micha0692.github.io/Actividades/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

**Que no fue claro de la actividad?**

**Como podríamos mejorarla?**

**Comment by lara-garbero-tais** [comment]
Esta re pro tu entrega, bien ahi! Actividad más que aprobada, gracias por la onda.
