### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by lucianamora** [CreemosEnLaRed/entregas#22]
Dirección de la actividad: https://lucianamora.github.io/actividad-1

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
El desafío de aprender y la paciencia que tuve que tener.
...

**Que no fue claro de la actividad?**
Tuve complicaciones con los brunchs porque no inferí que tenía que borrar el trabajo anterior
...

**Como podríamos mejorarla?**
Quizás encadenar lo de la clase anterior con lo nuevo ;)
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
