### ISSUE TITLE
https://mujeresactivando-web.github.io/actividad-01/pagina.html

### ISSUE THREAD

**Issue by MujeresActivando-web** [CreemosEnLaRed/entregas#23]
Dirección de la actividad: https://user.github.io/actividad

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by MujeresActivando-web** [comment]
hola, se me ha complicado muchisimo esta parte, tuve que rehacer mi cuenta. no lograba entender bien las consignas.

**Comment by MujeresActivando-web** [comment]
https://mujeresactivando-web.github.io/actividad-01/pagina.html

**Comment by MujeresActivando-web** [comment]
este es la direccion de la pagina que cree.

**Comment by lara-garbero-tais** [comment]
Se ve muy bien la pagina. Esta aprobada. 

Lo que si, fijate que en la linea 10 y 33 de index.html, en el enlace a la imagen, las subiste como para usar la ruta relativa pero pusiste la ruta absoluta. O sea, si tu imagen ya esta en tu directorio `/actividad-01/imagen/` podes poner directamente:
` <img src="imagen/20200218_154948_0000.png" alt="Mujeres Activando"> `
en vez de:
`<img src="https://github.com/MujeresActivando-web/MujeresActivando-web.github.io/blob/master/actividad-01/imagen/20200218_154948_0000.png?raw=true" alt="Mujeres Activando">`
(son equivalentes, apuntan a la misma)

**Comment by MujeresActivando-web** [comment]
Genial muchas gracias💪💪💪💪
