### ISSUE TITLE
https://cintialop.github.io/index.html

### ISSUE THREAD

**Issue by cintialop** [CreemosEnLaRed/entregas#24]
Dirección de la actividad: cintialop.github.io

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me encanta todo hasta ahora, estoy super enganchada con el curso. Me encanta ir entendiendo el código y su predisposición a ayudarnos

**Que no fue claro de la actividad?**

quizás no me quedó muy claro al principio que esta actividad se enganchaba con la de ingreso. Yo iría armando con los videos una pagina que se vaya complejizando en cada ejercicio. Es decir, que los ejemplos que da mariano sean ejemplos concretos de una pagina real, digo. Porque los ejemplos sueltos me hacen perder un poco.

**Como podríamos mejorarla?*
solo esto por ahora!
Gracias siempre!!!

**Comment by lara-garbero-tais** [comment]
Esta muy bien! actividad aprobada.
