### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by florenciaprios** [CreemosEnLaRed/entregas#25]
Dirección de la actividad: https://florenciaprios.github.io/florenciaprios.github.io/Actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Se ve re prolija tu actividad, aprobada! 

Despues podemos conversar mas los enlaces porque noto que hay varios enlaces absolutos que podrian ser relativos, porque son a tus propias imagenes y paginas. Entonces por ejemplo si tu `index.html` y tu `itinerario.html` estan en el mismo directorio y del primero enlazas al segundo, no hace falta poner el link completo `href='https://florenciaprios.github.io/florenciaprios.github.io/Actividad-1/itinerario.html'`, con `href='itinerario.html'` te alcanza (y te conviene porque si en algun punto moves el directorio completo el primero se rompe, el segundo no). 

De todos modos noto que es solo en los links de la navbar de bloques, no los que hiciste vos abajo, asi que por eso esta aprobada. Saludos!

**Comment by florenciaprios** [comment]
Comprendo, gracias Lara por tu corrección! Disculpa la demora en responder,
me había quedado tu mail en la carpeta de Spam y recién lo veo. Corrijo lo
que me señalaste y continúo con la última actividad. Saludos!
