### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by desileonardi** [CreemosEnLaRed/entregas#26]
Dirección de la actividad: https://desileonardi.github.io/actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Muy piola tu actividad, remil aprobada! Hasta la prox!

**Comment by desileonardi** [comment]
Mortyyy gracias!!!
