### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by LuciaArros** [CreemosEnLaRed/entregas#27]
Dirección de la actividad: https://luciaarros.github.io/actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Siento que cada vez entiendo un poco mejor, me resulta mas intuitivo, el programa.

**Que no fue claro de la actividad?**

Me sigue costando entender un poco lo de enlace relativo

**Como podríamos mejorarla?**

Creo que a lo largo del curso vamos a poder entenderlo mejor a eso

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
