### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by reneegallo** [CreemosEnLaRed/entregas#28]
Dirección de la actividad: https://reneegallo.github.io/actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
poder hacer la barra de navegacion
...

**Que no fue claro de la actividad?**
como ordenar nuestro github. termino con varias paginas en el branch master que no estan relacionadas entre si. 
...

**Como podríamos mejorarla?**
orden claro en los videos. entonces se puede ir haciendo a la par. aunque lo solucionaron con el ultimo video que subieron. 
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada
