### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by nadup** [CreemosEnLaRed/entregas#29]
Dirección de la actividad: https://nadup.github.io/Actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó la profundización en qué es el HTML y de qué se compone (la introducción más teórica digamos), esto le da sentido a la actividad que se desarrolla a continuación
...

**Que no fue claro de la actividad?**
Nada, todo super claro!
...

**Como podríamos mejorarla?**
Creo que con todos los medios de contacto con los que contamos, está buenísimo y no hace falta nada más. Sí destaco lo mismo que ya se dijo en el chat, manejarse con la lupita para buscar temas que ya se hablaron para no sobrecargar. Particularmente me costó bastante seguir el chat, directamente me puse a ver todos los videos en el canal de youtube pero no vi de qué consultas se derivaron.
...

**Comment by lara-garbero-tais** [comment]
Esta muy bien! Aprobada.
