### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Meryov7** [CreemosEnLaRed/entregas#3]
Dirección de la actividad: https://meryov7.github.io/act1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
**Que no fue claro de la actividad?**
**Como podríamos mejorarla?**

**Comment by marianoguerra** [comment]
Felicitaciones, primer entrega! :grinning:

**Comment by lara-garbero-tais** [comment]
Está muy bien compa, actividad aprobada!
