### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by anibliszeraus** [CreemosEnLaRed/entregas#31]
Dirección de la actividad: https://anibliszeraus.github.io/actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
si
...

**Que no fue claro de la actividad?**
Segui paso a paso el video explicativo de la actividad y me salio bien de una vez. Aun al leer las consignas me cuesta relacionar los terminos con los links adecuados..pero con el video fue muy claro y me ayuda a incorporar el lenguaje mas facilmente
...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
