### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by eugeniazorrilla** [CreemosEnLaRed/entregas#32]
Dirección de la actividad: https://eugeniazorrilla.github.io/actividad-1

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Ir entendiendo cómo interactúan los enlaces entre sí

**Que no fue claro de la actividad?**

Fue claro

**Como podríamos mejorarla?**

Para este paso está bien! Esperamos lo que viene. Gracias!

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
