### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by claucelr** [CreemosEnLaRed/entregas#33]
Dirección de la actividad: https://claucelr.github.io/actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Hola compa! Esta muy bien. Actividad aprobada.

Comentario con respecto a la imagen rota en el index, eso pasa porque la ruta relativa `img/rainbow.png` busca desde donde esta el archivo HTML que la llama (`index.html`), en este caso dentro del directorio` /actividad-1/`, y tu directorio `img` está fuera, en la raiz de tu repo, es decir un nivel mas arriba.

O sea: tu `index.html` busca:
`https://claucelr.github.io/actividad-1/img/rainbow.png`
y tu imagen esta en:
`https://claucelr.github.io/img/rainbow.png`
Para arreglar esto podes hacer dos cosas:
O crear un dir `/img/` dentro de `/actividad-1/` y ponerla ahi
O decirle a tu html que antes de buscar la imagen en `/img/` vaya un nivel para arriba. Esto se hace diciendo `..` - es decir, usando la ruta relativa:
`../img/rainbow.png` en vez de:
`img/rainbow.png`

Si no se entiende la explicacion preguntanos y lo vemos!
