### ISSUE TITLE
Entrega de  Actividad

### ISSUE THREAD

**Issue by Flor93** [CreemosEnLaRed/entregas#34]
Dirección de la actividad: https://flor93.github.io/actividad1/
Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Si, me encanto. Me quedan algunas dudas más relacionadas a los diseños y formatos de las imágenes. 

**Que no fue claro de la actividad?**

Muy claro todo

**Como podríamos mejorarla?**
 Yo creo que vamos perfectamente, al menos para mí me sirve que sean consignas puntuales y de a pasos pequeños.

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada. 

Con respecto a la imagen que no se ve porque es demasiado grande, ya vamos a ver bien como hacer para que se vea exactamente como queres, ocupe un porcentaje determinado de la pagina, etc. Por el momento para que se vea mejor podes agregarle a tu tag `<img src="logo mezcal.png" alt="imagen de...">` el atributo `width` (ancho) de esta forma:
`<img src="logo mezcal.png" width="1000" alt="imagen de...">`
Eso le dice, en pixels, de que ancho mostrarla (1000px en este caso). Tambien podes usar `height` para definir el alto, o los dos juntos (si usas uno solo el otro se calcula automaticamente). De todos modos no te conviene usar imagenes muy grandes y achicarlas asi porque si bien parecen mas chicas siguen siendo igual de pesadas y tardan mas en cargarse, pero todo eso es para despues, por lo pronto estamos!
