### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by SophiaUrbina** [CreemosEnLaRed/entregas#35]
Dirección de la actividad: https://sophiaurbina.github.io/Amazonas%20y%20Arp%C3%ADas/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...Pude crear mi página!! 

**Que no fue claro de la actividad?**

...
**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.

Con respecto a la URL de tu pagina (`https://sophiaurbina.github.io/Amazonas%20y%20Arp%C3%ADas/`), como no aceptan ni espacios ni caracteres especiales estos se codifican automaticamente a porcentajes y caracteres permitidos. Para que sea mas legible podrias por ejemplo renombrar tu directorio `/Amazonas y Arpías/` a `/amazonas-y-arpias/`, como para que tu URL quede como `https://sophiaurbina.github.io/amazonas-y-arpias/` . Pero eso es para mas adelante, por ahora todo bien!
