### ISSUE TITLE
entrega de actividad

### ISSUE THREAD

**Issue by leicba** [CreemosEnLaRed/entregas#36]
Dirección de la actividad: https://leicba.github.io/AL-NOTICIAS/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Que empecé a entender y a registrar más los códigos HTML, me animé a tocar un poco más todo.

**Que no fue claro de la actividad?**
Fue clara la actividad, al principio me costó asimilar porque tuve que recordar y repasar lo de la primera que no lo tenía tan presente, entonces tuve que ver varias veces los videos, pero salió.

**Como podríamos mejorarla?**
Para mi esta super completo, por ahí sumaría alguna guía escrita con lo básico y más importante, pero hasta ahora con las herramientas que hay me pude manejar bastante bien, o eso sentí.
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.

**Comment by leicba** [comment]
Gracias!! :)
