### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by clara-reyna** [CreemosEnLaRed/entregas#37]
Dirección de la actividad: https://clara-reyna.github.io/Actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó la inclusión de los nuevos contenidos. Nose como estamos como grupo en gral, pero por las dudas lo tiro para que lo analicen.. Me gustaría conocer un poco más sobre contenedores dentro del html.

**Que no fue claro de la actividad?**
Los videos por momentos pueden ser un poco confusos porque a veces figurar errores que no se explican y no queda claro.

**Como podríamos mejorarla?**
Un poquitito más de claridad en los videos y en los casos de surgir un error explicar que sucedió (siempre y cuando sea algo que se pueda explicar, no por cosas extraordinarias, que el servidor se cayo o cosas así). 

El resto un éxito, pilaa de ganas de seguir aprendiendo

**Comment by lara-garbero-tais** [comment]
Está muy bien compa! Se nota que te quedó re claro. Actividad aprobada!
