### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by lucianaprogramadora** [CreemosEnLaRed/entregas#38]
Dirección de la actividad: https://lucianaprogramadora.github.io/actividad1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Todo . entendi mas el manejo de git hub para ordenar los procesos y como herramienta tambien
ahora me quedo todo mas en claro sobre esa pagina. 

**Que no fue claro de la actividad?**

No termine de entender el enlace relativo, vi los videos y  si entendi la consigna y como realizarlo pero el concepto no me quedo del todo claro creo que es lo que me cuesta entender un poco mas de concepto pero por mi forma de aprender calculo.

**Como podríamos mejorarla?**

en telegram anclando mensajes cuando se explican procesos o detalles de para que sirve cada herramienta se me ocurre

**Comment by lara-garbero-tais** [comment]
Hola Luciana! Esta muy piola la web, te falta una sola cosa y es que todos los titulos del HTML son el Mi Pagina que viene standard de Bloques. Una de las consignas es que alguna de todas las pags tenga otro titulo. A esto lo logras cambiando la linea 5 de alguno de tus archivos HTML de `<title>Mi Pagina</title>` a `<title>Otra Cosa</title>`.
Pero en general bien! aprobada.

**Comment by lucianaprogramadora** [comment]
Hola sii pensé que lo había cambiado pero modifique un montón e veces cada
página y me debe haber quedado perdida porque me parece que si le.cambie .
Mortal gracias
