### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by carmencabezas** [CreemosEnLaRed/entregas#39]
Dirección de la actividad: https://carmencabezas.github.io/actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
aprender el lenguaje html

**Que no fue claro de la actividad?**
el video dos iba muy rápido al momento de explicar de lo del directorio

**Como podríamos mejorarla?**
Mejorar el volumen del audio :) 
...

**Comment by lara-garbero-tais** [comment]
Clarisimo, actividad aprobada!
