### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by seleneagomez** [CreemosEnLaRed/entregas#4]
Dirección de la actividad: https://seleneagomez.github.io/Actividad-1

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gusto haber entendido muy bien como incorporar una imagen que era algo que me tuvo en duda durante la actividad de inicio y comprender como se compone una pagina en la vida real jaja
...

**Que no fue claro de la actividad?**
No me parecieron tan claros los conceptos de rutas absolutas y relativas cuando se hablaba en terminos "desde aca". Mas allá de eso,todo perfecto
...

**Como podríamos mejorarla?**
Quizás planificar un poco más las clases via video pero no quiero ser exigente con sus tiempos personales
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
