### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by barbidominguez** [CreemosEnLaRed/entregas#40]
Dirección de la actividad: https://barbidominguez.github.io/Actividad%201/

Soy oyente? No (sí hice el ingreso)

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me pareció muy bueno que hayamos visto los enlaces relativos y absolutos, super útil.

**Que no fue claro de la actividad?**
Muy claro en lineas generales, pensé que no habia entendido lo de la imagen cuando esta en el repositorio, pero sólo demoraba en cargar. 

**Como podríamos mejorarla?**
Un poco bajo el audio de los videos, pero también puede ser mi parlante.

**Comment by lara-garbero-tais** [comment]
Hola compa! Está bien la actividad, está aprobada!
A esto aún no lo vimos, pero ya que te interesa te cuento que si querés crear un enlace para mandar un email podes usar un enlace mailto.
En tu caso, en vez de poner
`<a href="www.gmail.com">:(</a>`
podes poner
`<a href="mailto:mail.de.barbi@gmail.com">:(</a>`
Y si quien lo clickee está desde el celu o tiene instalado un cliente de email tipo outlook, le va a abrir un mail en blanco con la dirección ya puesta para que te escriba. Saludos!

**Comment by barbidominguez** [comment]
Hola! Mil gracias por la respuesta y el laburo! Les hago una consulta, yo
puse ese enlace a gmail porque mi idea era que ella entre a su gmail.
Porque conocía la opción de mailto pero el tema es que casi nadie tiene
outlook. Bueno eso, no sé, si habrá otra forma de hacerlo que dirija a su
mail.
De todas formas realmente gracias por tomarse el tiempo de leer el código y
devolver.
Abrazo virtual !!

Barbi
