### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Florigarola** [CreemosEnLaRed/entregas#41]
Dirección de la actividad: https://florigarola.github.io/Actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó mucho la claridad con la que fue explicada y los videos extra para profundizar en información accesoria que puede ser de utilidad. Me gustó comenzar con una actividad simple y accesible.
Aprovecho para decir que la hice bastante a las apuradas y por eso quedó muy simple y sin desarrollar, pido disculpas por eso pero la idea es seguir editando y mejorando mi idea principal.
...

**Que no fue claro de la actividad?**
Tuve que reveer varias veces los videos porque me costó lograr insertar el link relativo. Quise hacerlo con una imagen pero no pude, sólo me salió insertarla mediante link absoluto, y como en los videos se explica sólo en caso de usar una imagen ya presente en la página (el arcoiris), no me quedó del todo claro si se podía hacer con una foto propia. De todos modos sacando eso que pudo haber sido un error de interpretación mío, el resto de los videos explicativos estuvieron muy bien!
...

**Como podríamos mejorarla?**
De ninguna manera, la disfruté mucho. Gracias!
...

**Comment by lara-garbero-tais** [comment]
Esta re bien Rolf! 

Con respecto a tu pregunta, para insertar la imagen como relativa lo haces cambiando 
`<img class="card-img-top" src="https://florigarola.github.io/Actividad-1/DSC_0094.JPG" alt="Hojitas">`
por
`<img class="card-img-top" src="DSC_0094.JPG" alt="Hojitas">`
Al tenerla cargada en el mismo directorio que el archivo HTML desde el que la estas llamando solo tenes que decir su nombre, y fue.

**Comment by Florigarola** [comment]
¡Gracias Lara! :) ;)
