### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Montesdearrabal** [CreemosEnLaRed/entregas#42]
Dirección de la actividad: https://montesdearrabal.github.io/PlantaSanta/index.html

Soy oyente? No lo se! empece tarde, creeria que si.

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Si, me pareció divertida y desafiante. Miré muchas veces algunos videos y las consignas!
...

**Que no fue claro de la actividad?**
Al principio me fue dificil entenderla pero con los videos fui comprendiendo todo. En mi caso tengo dificultad con los margenes de los textos o imagenes.
...

**Como podríamos mejorarla?**
Me parece que fue completa! 
...

**Comment by lara-garbero-tais** [comment]
Actividad aprobada. Está muy bien!
