### ISSUE TITLE
Entrega Actividad 1

### ISSUE THREAD

**Issue by vanpin** [CreemosEnLaRed/entregas#43]
Dirección de la actividad: https://vanpin.github.io/actividad1

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**
Me gustaria que bloques web guarde el trabajo de las distintas paginas. Seria mas practico
...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
