### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by florensiatoledo** [CreemosEnLaRed/entregas#44]
Dirección de la actividad: https://florensiatoledo.github.io/ACtividad-1/
Soy oyente? no

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Cerrada por alumnx, tal vez por error? Reabro para evaluarla.

**Comment by lara-garbero-tais** [comment]
Vi que era repetida, cerrando
