### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by florensiatoledo** [CreemosEnLaRed/entregas#45]
Dirección de la actividad: https://florensiatoledo.github.io/ACtividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden, actividad aprobada.

Observacion, las imagenes que se te rompen es porque te falta el archivo `rainbow,png` en tu repo. Si guardas cualquier archivo con ese nombre donde tenes `index.html` y` pagina.html` eso se soluciona. Saludos!
