### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by marianoe49** [CreemosEnLaRed/entregas#46]
Dirección de la actividad: https://marianoe49.github.io/Activdad1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Entender un poco más sobre HTML

**Que no fue claro de la actividad?**
Me enredé un poco en entender por un lado el funcionamiento de github y por el otro el funcionamiento de bloques web. 

**Como podríamos mejorarla?**

Está bastante bien, super intuitivo el uso de ambos. Quizás facilitar recursos para estudiar algo más general sobre web y html.

**Comment by lara-garbero-tais** [comment]
Todo en orden. Actividad aprobada!
