### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by guillerminaazul** [CreemosEnLaRed/entregas#48]
Dirección de la actividad: guillerminaazul.github.io/cancionesazules/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Hola compa! Fijate que te faltan algunas consignas. A los enlaces absolutos y relativos los tenes pero falta:
1) Crear otro archivo HTML y enlazar al segundo desde el primero.
2) Cambiar el nombre de alguno de ellos a algo que no sea 'Mi Pagina'. A esto lo podes hacer cambiando la linea 5 de tu archivo HTML de:
`<title>Mi Pagina</title>`
a
`<title>Otra cosa</title>`
Si te perdes avisa y lo vemos!

**Comment by guillerminaazul** [comment]
Gracias! intento ponerme mañana, pero la verdad es que me costó bastante y justo estas indicaciones que me das, creí que las había solucionado. Seguro necesitaré ayuda, porque es todo muy nuevo pa mi, jaja. Gracias de nuevo y abrazo 
    El domingo, 29 de marzo de 2020 05:19:17 ART, Lara Tais <notifications@github.com> escribió:  
 
 


Hola compa! Fijate que te faltan algunas consignas. A los enlaces absolutos y relativos los tenes pero falta:
   
   - Crear otro archivo HTML y enlazar al segundo desde el primero.
   - Cambiar el nombre de alguno de ellos a algo que no sea 'Mi Pagina'. A esto lo podes hacer cambiando la linea 5 de tu archivo HTML de:   
<title>Mi Pagina</title>   
a   
<title>Otra cosa</title>   
Si te perdes avisa y lo vemos!

**Comment by guillerminaazul** [comment]
Creo que está corregido, si alguien puede, me avisaría si ya está bien?

    El martes, 31 de marzo de 2020 20:44:11 ART, Maria Guillermina Abalos <guilleab03@yahoo.com.ar> escribió:  
 
  Gracias! intento ponerme mañana, pero la verdad es que me costó bastante y justo estas indicaciones que me das, creí que las había solucionado. Seguro necesitaré ayuda, porque es todo muy nuevo pa mi, jaja. Gracias de nuevo y abrazo 
    El domingo, 29 de marzo de 2020 05:19:17 ART, Lara Tais <notifications@github.com> escribió:  
 
 


Hola compa! Fijate que te faltan algunas consignas. A los enlaces absolutos y relativos los tenes pero falta:
   
   - Crear otro archivo HTML y enlazar al segundo desde el primero.
   - Cambiar el nombre de alguno de ellos a algo que no sea 'Mi Pagina'. A esto lo podes hacer cambiando la linea 5 de tu archivo HTML de:   
<title>Mi Pagina</title>   
a   
<title>Otra cosa</title>   
Si te perdes avisa y lo vemos!

**Comment by marianoguerra** [comment]
aprobado!
