### ISSUE TITLE
noelia-corralpaz.github.io/actividad.1

### ISSUE THREAD

**Issue by noelia-corralpaz** [CreemosEnLaRed/entregas#49]
Dirección de la actividad: https://noelia-corralpaz.github.io/actividad.1

Soy oyente? Si

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
que finalmente entendí!
...

**Que no fue claro de la actividad?**
al principio sentí que iba muy rápido, los videos que se fueron a agregando explicando a que hacía referencia la terminología usada sirvieron mucho.
...

**Como podríamos mejorarla?**
desglosando las actividades en videos más cortos sobre aspectos puntuales
...

**Comment by lara-garbero-tais** [comment]
Cerrada por alumnx, tal vez por error? Reabro para evaluarla.

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.

**Comment by noelia-corralpaz** [comment]
Hola! Si yo la cerré pensé que era como terminar de subirla o algo así.  😧
Perdón je. Lo subo de nuevo o algo??

**Comment by noelia-corralpaz** [comment]
Ay genial! Muchas gracias por todooo
