### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by pmzazu** [CreemosEnLaRed/entregas#5]
Dirección de la actividad: https://pmzazu.github.io/PaginaCarlos/contacto.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó que entendí cómo generar varias paginas unidas por un nav
...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**
 quizas empezar a aprender algo de estilos o de codigo
...

**Comment by lara-garbero-tais** [comment]
Se ve muy bien la actividad, compa! Está aprobada. La única duda que me surge es por qué tu index se llama `indexC.html` en vez de solo `index.html`, que haria que la página principal se pueda ver en  `https://pmzazu.github.io/PaginaCarlos/` sin necesidad de especificar la ruta hasta el archivo HTML `https://pmzazu.github.io/PaginaCarlos/indexC.html`

**Comment by pmzazu** [comment]
Hola!! Gracias!
Le había puesto la C porque en mi cabeza podia distinguirla del index de la
actividad anterior. Pero genial dato que sea indistinto e incluso mas útil
solo ponerle el index!!

**Comment by lara-garbero-tais** [comment]
Tiene sentido! Pero cada directorio usa su propio index.html, no es un problema que se repita el nombre. Saludos!
