### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by avivinetto** [CreemosEnLaRed/entregas#50]
Dirección de la actividad: https://avivinetto.github.io

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Que para mi todo es nuevo, asi que estoy aprendiendo mucho.

**Que no fue claro de la actividad?**
Recibi el mail de la primera acitividad (con el link), pero no de la introduccion, por lo que no entendía qué era Github y bloques Web. Despues me di cuenta que habia una actividad introductoria. En agun momento se mencionó Telegram (creo), pero no recibí mail respecto a eso.

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Todo en orden! Actividad aprobada.
