### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by ivi-cvj1** [CreemosEnLaRed/entregas#51]
Dirección de la actividad: https://ivi-cvj1.github.io/actividad-1/index.html

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me encanta la forma de enseñar, muy práctica y la capacidad de ver como se puede interactuar entre páginas a través de los distintas formas de enlaces.

...

**Que no fue claro de la actividad?**
Por momentos me pierdo al escuchar las consignas, siguiendo el paso a paso a veces en esas modificaciones de último momento o los detalles sobre algunas modificaciones simples son  rápidas y al no estar familiarizada aún me cuesta seguir el ritmo. 

...

**Como podríamos mejorarla?**
Considero que es un problema principalmente de eso, no estar del todo familiarizada aún con el lenguaje, de todas formas ir más en detalle en las modificaciones que se hacen sobre pasos ya hechos me sería útil. 

...

**Comment by nykka** [comment]
Hola! Habría que revisar algunas cosas.
La parte de la URL relativa no está funcionando. Fijate que cuando hago click en Pagina, me da error. Eso es porque falta crear el archivo `página.html`. 
![Screen Shot 2020-04-10 at 12 10 20](https://user-images.githubusercontent.com/8450941/79001105-4aab4980-7b24-11ea-954a-823109e4b8d0.png)

Como falta eso, tampoco podemos chequear otra de las consignas que es "Una de las paginas tiene que tener un titulo que no sea Mi Pagina".

Por otro lado, hay una imagen que no está cargando, revisa la URL relativa de está imagen y que ésta esté subida a la misma carpeta de la actividad.
![Screen Shot 2020-04-10 at 12 10 11](https://user-images.githubusercontent.com/8450941/79001125-5139c100-7b24-11ea-95d4-70b188f9059a.png)

**Comment by ivi-cvj1** [comment]
Gracias! Me fijo y la envío hoy entonces. Saludos!

Enviado desde mi smartphone Sony Xperia™

---- Veronica escribió ----


Hola! Habría que revisar algunas cosas.
La parte de la URL relativa no está funcionando. Fijate que cuando hago click en Pagina, me da error. Eso es porque falta crear el archivo página.html.
[Screen Shot 2020-04-10 at 12 10 20]<https://user-images.githubusercontent.com/8450941/79001105-4aab4980-7b24-11ea-954a-823109e4b8d0.png>

Como falta eso, tampoco podemos chequear otra de las consignas que es "Una de las paginas tiene que tener un titulo que no sea Mi Pagina".

Por otro lado, hay una imagen que no está cargando, revisa la URL relativa de está imagen y que ésta esté subida a la misma carpeta de la actividad.
[Screen Shot 2020-04-10 at 12 10 11]<https://user-images.githubusercontent.com/8450941/79001125-5139c100-7b24-11ea-95d4-70b188f9059a.png>

**Comment by marianoguerra** [comment]
aprobado!
