### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by victoriaemaldonado** [CreemosEnLaRed/entregas#52]
Dirección de la actividad: victoriaemaldonado.github.io/actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Crear links a nuevas páginas.
...

**Que no fue claro de la actividad?**

Al principio no sabía que debía poner / después de actividad-1 para que se desplazara como nombre de directorio.
Si para cada nuevo inicio borramos los bloques anteriormente creados. No me animaba a hacerlo porque temía perder la actividad de ingreso, la descargué de todas formas en mi compu.

...

**Como podríamos mejorarla?**
...

**Comment by nykka** [comment]
Todo en orden! Actividad aprobada.
