### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by gachifernandez** [CreemosEnLaRed/entregas#53]
Dirección de la actividad: https://gachifernandez.github.io/actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...Que se empiezan a abrir más posibilidades para crear.

**Que no fue claro de la actividad?**

...Creo que la explicación de enlaces relativos y absolutos se complicó un poco. Los videos en gral de esta actividad me parecieron más claros y concisos que los anteriores.

**Como podríamos mejorarla?**

...Con bibliografía complementaria, links para ampliar la info de manera un poco más teórica para quien tenga ganas. Sé que puedo buscar yo pero estaría bueno tener una referencia de algo que sea simple de entender.

**Comment by nykka** [comment]
Hola!
Faltaría una sola cosa de las consigas: Una de las paginas tiene que tener un titulo que no sea Mi Pagina.
Fijate que tu página Artistas sigue teniendo el título "Mi Pagina".
![Screen Shot 2020-04-10 at 12 17 18](https://user-images.githubusercontent.com/8450941/79001670-4895ba80-7b25-11ea-91ab-0291806b41da.png)

**Comment by gachifernandez** [comment]
Listo, gracias!!!

**Comment by nykka** [comment]
Perfecto!
