### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Nadiaf81** [CreemosEnLaRed/entregas#54]
Dirección de la actividad: https://nadiaf81.github.io/Actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me gustó hacerlo xq es algo nuevo y estoy muy entusiasmada en aprender. 

**Que no fue claro de la actividad?**

En los videos siento que va muy rápido, y como es la primera vez que estoy en esto me cuesta seguir las explicaciones.

**Como podríamos mejorarla?**

Creo que haciendo un poco más lenta la explicación y mostrando más en detalle los pasos a seguir.

**Comment by nykka** [comment]
Todo en orden! Actividad aprobada.

Un sólo comentario a modo de recomendación. Los archivos como `vuelo en Capadocia.jpg` es mejor nombrarlos `vuelos-en-capadocia.jpg`, o sea sin espacios y/o mayúsculas.

**Comment by Nadiaf81** [comment]
Buenísimo. Gracias por la recomendación.
