### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by Juliraf20** [CreemosEnLaRed/entregas#55]
Dirección de la actividad: https://juliraf20.github.io/Actividad-1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

La libertad de poder poner lo que quisieramos (pero de alguna forma siguiendo un orden)

**Que no fue claro de la actividad?**

Por ahí al principio me costo mucho entender bien las consignas, no me quedaba claro que habia que entregar. En el primer video no se entendia muy bien, y en el segundo entendi con mas claridad.

**Como podríamos mejorarla?**

Ya lo mejoraron :)

**Comment by nykka** [comment]
Todo en orden! Actividad aprobada.
