### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by RominaSo** [CreemosEnLaRed/entregas#57]
Dirección de la actividad: http://rominaso.github.io/actividad2/actividad2.bloques

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
:clap: aprobado!

**Comment by RominaSo** [comment]
Gracias =)
