### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by gachifernandez** [CreemosEnLaRed/entregas#58]
Dirección de la actividad: gachifernandez.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Seguir avanzando en HTML
...

**Que no fue claro de la actividad?**

...Me parece que estaría buena una explicación básica más lenta sobre qué es un tag y un atributo y como se arma el código.

**Como podríamos mejorarla?**
Con links a bibliografía de referencia o a alguna página que sea fácil de entender para principiantes
...

**Comment by marianoguerra** [comment]
casi perfecto :) fijate que en la segunda imagen pusiste una dirección a una imagen que no existía, si la cambias por la dirección de la primera funciona.

aprobada igual!
