### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by ivi-cvj1** [CreemosEnLaRed/entregas#59]
Dirección de la actividad: https://ivi-cvj1.github.io/Actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...Muy bien explicada, me pareció findamental ver el video introductorio donde se especificaba para qué sirve cada lenguaje y cómo utilizarlo.

**Que no fue claro de la actividad?**

...nada! fué dinámica y entendible.

**Como podríamos mejorarla?**

...más ejercicios!.

**Comment by marianoguerra** [comment]
:1st_place_medal: buenisimo que hiciste todos con los dos tipos de bloques.

aprobada!
