### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by avivinetto** [CreemosEnLaRed/entregas#60]
Dirección de la actividad: https://avivinetto.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Es una actividad simple pero que me sirvió mucho para empezar a entender el lenguage html. 

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
perfecto, buenisimo que hiciste todos los ejemplos con los dos tipos de bloques

aprobada!
