### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by MujeresActivando-web** [CreemosEnLaRed/entregas#62]
Dirección de la actividad: MujeresActivando-web.github.io /actividad2/

https://github.com/MujeresActivando-web/MujeresActivando-web.github.io/blob/master/actividad2/actividad2.bloques.bloques

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by MujeresActivando-web** [comment]
https://mujeresactivando-web.github.io/actividad2/

**Comment by marianoguerra** [comment]
perfecto :1st_place_medal:  aprobada!
