### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by luchicarioni** [CreemosEnLaRed/entregas#63]
Dirección de la actividad: https://luchicarioni.github.io/actividad2

luchicarioni.github.io/actividad2/Actividad2.bloques 

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
buenisimo! cuanta azucar es mucha azucar? :smile: 

aprobada!
