### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by seleneagomez** [CreemosEnLaRed/entregas#64]
Dirección de la actividad: https://seleneagomez.github.io/actividad2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
muy linda como quedo la pagina :)

observaciones:
* un tag de link tiene el atributo y el contenido vació 
* te falto hacer la lista con los bloques de mas bajo nivel.
* te falto hacer la imagen con los bloques de mas bajo nivel.

**Comment by marianoguerra** [comment]
aprobado!
