### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by Remoraland** [CreemosEnLaRed/entregas#67]
Dirección de la actividad: https://remoraland.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me resultó mucho más fácil que la 1!
...

**Que no fue claro de la actividad?**

...Todo estuvo súper claro.

**Como podríamos mejorarla?**

...Mejoraron mucho los videos, al explicar las fases mas lentamente. Gracias!

**Comment by marianoguerra** [comment]
perfecto, muy linda la imagen :)

aprobada!
