### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by clara-reyna** [CreemosEnLaRed/entregas#68]
Dirección de la actividad: https://clara-reyna.github.io/Actividad-2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Tener que escribir parte de mi propio HTML 
...

**Que no fue claro de la actividad?**
Fue muy clara.. aunque intenté resolverla de otra manera 
...

**Como podríamos mejorarla?**
Me pasa que por momentos no me siento del todo desafiada e intento cumplir las actividades con algún condimento nuevo.. ver que puedo explorar, que le puedo agregar, etc Nada wow igual jaja
Sería buenísimo si siguen compartiendo videos, explicaciones de distintos contenidos porque eso me sirve para profundizar un poco más y seguir aprendiendo.  
...

**Comment by marianoguerra** [comment]
buenísima tu pagina, felicitaciones!

mas que aprobada :)

sobre agregarle mas cosas, totalmente, ahora la actividad 3 ya escribimos HTML directamente, así que te vas a podre expresar libremente con todo el poder del lenguaje :)
