### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by florenciamelina** [CreemosEnLaRed/entregas#7]
Dirección de la actividad: https://florenciamelina.github.io/elovarioanarco/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden compa! Aprobada. 

Mi duda es por qué si tenias tu nuestrasredes.html andando no linkeaste a esa, calculo que es porque la imagen esta rota? 

Eso pasa porque la ruta relativa `img/33921608_2345861288973790_5727048897319141376_o.png` busca desde donde esta el archivo HTML que la llama (`nuestrasredes.html`), en este caso dentro del directorio `/elovarioanarco/`, y tu directorio img está fuera, en la raiz de tu repo, es decir un nivel mas arriba. 

O sea: tu `nuestrasredes.html` busca:
`https://florenciamelina.github.io/elovarioanarco/img/33921608_2345861288973790_5727048897319141376_o.png`
y tu img esta en:
`https://florenciamelina.github.io/img/33921608_2345861288973790_5727048897319141376_o.png`
Para arreglar esto podes hacer dos cosas:
O crear un dir `/img/` dentro de `/elovarioanarco/` y ponerla ahi
O decirle a tu html que antes de buscar la imagen en `/img/` vaya un nivel para arriba. esto se hace diciendo `..` - es decir, usando la ruta relativa:
`../img/33921608_2345861288973790_5727048897319141376_o.png` en vez de:
`img/33921608_2345861288973790_5727048897319141376_o.png`

Si no se entiende la explicacion preguntanos y lo vemos!
