### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by ro-mana** [CreemosEnLaRed/entregas#70]
Dirección de la actividad: https://ro-mana.github.io/actividad2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Me gustó que ya hayamos empezado a pensar en el código html, y que lo hagamos en niveles porque te permite comprender mucho más fácilmente cómo funciona.
Y gracias por estar siempre atentxs a nuestras preguntas!!

**Que no fue claro de la actividad?**

No sé si la actividad debería verse en la página principal que habíamos creado (por ejemplo si había que crear una pestaña que diga actividad 2) Quizás estaba dicho y se me pasó.

**Como podríamos mejorarla?**
-

**Comment by marianoguerra** [comment]
buenisimo que hiciste todos los tags con los dos tipos de bloques

no habia que agregar un link de la pagina principal.

aprobada!
