### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by nadup** [CreemosEnLaRed/entregas#71]
Dirección de la actividad: [https://github.com/nadup/nadup.github.io/tree/master/Actividad-2](url)

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
La facilidad que brinda Bloques Web para ir "bajando" hasta llegar a escribir código HTML. Aparte de esto, me enganché muchísimo con el resto de los videos extra (no específicos de las actividades) que no había tenido tiempo de ver antes, muchísimas gracias por tanto material interesante y por tratar de encontrarle siempre la vuelta para que los contenidos sean más comprensibles y amigables!

**Que no fue claro de la actividad?**
Primero leí la consigna escrita y no entendí nada, pero con los videos se super entendió no sólo el procedimiento sino el por qué y para qué de la actividad

**Como podríamos mejorarla?**

**Comment by marianoguerra** [comment]
muy bueno que hiciste todos los bloques con los dos tipos

me quedo pensando si las cosas de la lista son ingredientes de algo :smile: 

aprobada!
