### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by guillerminaazul** [CreemosEnLaRed/entregas#74]
Dirección de la actividad: https://guillerminaazul.github.io/actividad-2.bloques

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me pareció más sencilla que las demas y los videos junto a las imagenes me aclararon bastante las dudas.
...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Hola Guillermina, el ejercicio está bien, pero fijate que las imágenes no se están viendo.
