### ISSUE TITLE
Entrega de Actividad 3 - <Mery Oviedo>

### ISSUE THREAD

**Issue by Meryov7** [CreemosEnLaRed/entregas#76]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad:Meryov7.github.io/actividad3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Hola! Te hago una observación y una sugerencia, y te adjunto una imagen para que sea más claro.
Linea 22 y 29. El elemento `<input></input>` debería estar por fuera (Y debajo) del `<div>` donde se encuentra ahora. 
![Screen Shot 2020-04-24 at 11 48 13](https://user-images.githubusercontent.com/8450941/80228860-f923b400-8625-11ea-8fac-8ac2afe43ab0.png)

Aparte, como consejo, te recomiendo que ajustes la indentación (los espacios a la derecha en cada linea) para que sea más fácil leer el código.
Te adjunto una imagen de como está ahora y como se vería con una correcta indentación para que puedas ver a lo que me refiero.
![Screen Shot 2020-04-24 at 12 11 13](https://user-images.githubusercontent.com/8450941/80228910-0e004780-8626-11ea-8274-2bce91d4d05b.png)

**Comment by marianoguerra** [comment]
aprobado!
