### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by Juliraf20** [CreemosEnLaRed/entregas#77]
Dirección de la actividad: https://juliraf20.github.io/Actividad2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Me gustó el hecho de poder entender más cómo hacer las cosas. Fue mucho más interactivo que la actividad anterior y me sirvió para entender más los conceptos.
...

**Que no fue claro de la actividad?**

Al principio no entendí si habia que replicarlo dos veces o una sola. 

**Como podríamos mejorarla?**

Fue un error mío por ver primero el primer video (que creo que se replico 2 veces) y no leer primero la actividad.

**Comment by nykka** [comment]
Hola! Tendrías que rehacer la parte de la lista, ya que en ambos casos estás utilizando el bloque lista:
![Screen Shot 2020-05-05 at 18 06 01](https://user-images.githubusercontent.com/8450941/81116130-39731400-8efb-11ea-993e-910e7bd5eb37.png)

**Comment by Juliraf20** [comment]
Hola verónica! Ya la corregí, la subi como actividad2.bloquescorregida<https://github.com/Juliraf20/Juliraf20.github.io/blob/master/Actividad2/actividad2.bloquescorregida> . Muchas gracias y saludos!

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Veronica <notifications@github.com>
Enviado: Tuesday, May 5, 2020 6:07:28 PM
Para: CreemosEnLaRed/entregas <entregas@noreply.github.com>
Cc: Juliraf20 <julietarafeto@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [CreemosEnLaRed/entregas] Entrega de Actividad 2 (#77)


Hola! Tendrías que rehacer la parte de la lista, ya que en ambos casos estás utilizando el bloque lista:
[Screen Shot 2020-05-05 at 18 06 01]<https://user-images.githubusercontent.com/8450941/81116130-39731400-8efb-11ea-993e-910e7bd5eb37.png>

**Comment by nykka** [comment]
Perfecto!
