### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by trinidadtomasini** [CreemosEnLaRed/entregas#78]
Dirección de la actividad: https://trinidadtomasini.github.io/actividad2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

No sé si corresponde a esta actividad puntual. Pero el tema de los brachs no lo entiendo, no es que quiera saber todo ahora pero hay cosas que no sé si están bien porque elegí el branch incorrecto o no

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Perfecto!
