### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by carmencabezas** [CreemosEnLaRed/entregas#79]
Dirección de la actividad: https://carmencabezas.github.io/actividad2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

si :)

**Que no fue claro de la actividad?**

si 

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Hola!, el ejercicio está bien pero fijate que las imágenes no se están viendo.
