### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by trinidadtomasini** [CreemosEnLaRed/entregas#8]
Dirección de la actividad: https://trinidadtomasini.github.io/entregaa1/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by lara-garbero-tais** [comment]
Todo en orden! Actividad aprobada.
