### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by melaniepriscila** [CreemosEnLaRed/entregas#83]
Dirección de la actividad: melaniepriscila.github.io/actividad2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Hola! El ejercicio está correcto. La única observación que te haría es que dentro de un tag `<ul></ul>` o `<ol></ol>` no puede ir un tag `<p></p>`. De hecho, si te fijas, el navegador lo va a mover por fuera de la lista:
![Screen Shot 2020-05-05 at 18 19 46](https://user-images.githubusercontent.com/8450941/81117194-134e7380-8efd-11ea-94ec-0bfec703ff63.png)
