### ISSUE TITLE
Entrega de Actividad 3 - <Ivi>

### ISSUE THREAD

**Issue by ivi-cvj1** [CreemosEnLaRed/entregas#84]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://ivi-cvj1.github.io/Actividad-3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

... Muy entretenida, poder perderme y encontrar dónde estaba el error me hizo ver que es un trabajo muy minucioso y que requiere de mucha atención.

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
le falta el borde al segundo ejemplo pero es un detalle, aproabada! :grinning:

**Comment by marianoguerra** [comment]
:alien:

**Comment by ivi-cvj1** [comment]
XD
