### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by cordobake** [CreemosEnLaRed/entregas#86]
Dirección de la actividad: https://cordobake.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

La diversidad para trabajar con diferentes herramientas

**Que no fue claro de la actividad?**

Todo claro

**Como podríamos mejorarla?**

Generar actividades sin explicación previa para la indagación.

**Comment by nykka** [comment]
Perfecto!
