### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by marianoe49** [CreemosEnLaRed/entregas#88]
Dirección de la actividad: marianoe49.github.io/actividad2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Poder entender más de html

**Que no fue claro de la actividad?**

Me cuesta enternder desde lo abstracto, pero cuando lo pongo en práctica se aclaran los conceptos. 

**Como podríamos mejorarla?**

Las imágenes me ayudan, y los videos también.

**Comment by nykka** [comment]
Perfecto!
