### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by Montesdearrabal** [CreemosEnLaRed/entregas#89]
Dirección de la actividad:https://montesdearrabal.github.io/actividad2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?** Me gusta que al principio cuando leo las consignas no entiendo nada y despues se aclara todo con los videos! 

...

**Que no fue claro de la actividad?**
Todo claro.
...

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Perfecto!
