### ISSUE TITLE
Entrega de Actividad

### ISSUE THREAD

**Issue by luchicarioni** [CreemosEnLaRed/entregas#9]
Dirección de la actividad: https://luchicarioni.github.io/actividadmarzo/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**
Crear y que finalmente salga
...

**Que no fue claro de la actividad?**
La diferencia entre barra de navegación y enlace
...

**Como podríamos mejorarla?**
Me parece que podría ayudar poner un recuadro o una lista de contenidos a destacar como forma de recordar mas fácilmente (sobre todo para la prox actividad) 
Muchas gracias!
...

**Comment by lara-garbero-tais** [comment]
Hola compa! Hay un par de errores en tu entrega, queres arreglarlos y avisarnos?

Para empezar, https://luchicarioni.github.io/actividadmarzo/ apunta a tu index.html, que no cumple la consigna ya que todos los enlaces usan rutas absolutas (a paginas externas). Puede ser que hayas querido decir https://luchicarioni.github.io/actividadmarzo/pagina.html?

Tu archivo pagina.html esta mas cerca de cumplir las consignas, tiene dos errores:

1) Tu enlace relativo (nav-item de las lineas 22 a 24) esta fuera de tu navbar. Tu navbar abre en la linea 12 y cierra en la linea 20, y tiene el primer item adentro y el segundo afuera. Pone tu enlace relativo dentro de la navbar, al mismo nivel que el absoluto (nav-item de las lineas 15 a 17), empezando en la linea 18.

2) Tu enlace relativo anda, pero no tiene un texto para mostrar. Ponele algo entre las etiquetas '<a class="nav-link" href="pagina.html">' y '</a>' asi se ve!

Con esto estamos! Avisanos cualquier cosa.

**Comment by luchicarioni** [comment]
Hola cumpa... a ver si esta bien ahi. 

https://luchicarioni.github.io/actividadmarzo/pagina.html

Esto me hizo dudar, le agregue "observemos" pero no se visualiza... 

2.Tu enlace relativo anda, pero no tiene un texto para mostrar. Ponele algo entre las etiquetas '' y '' asi se ve!

**Comment by marianoguerra** [comment]
aprobado!
