### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by eugeniazorrilla** [CreemosEnLaRed/entregas#90]
Dirección de la actividad: https://eugeniazorrilla.github.io/actividad2

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

animarse a escribir (aunque sea copiando)

**Que no fue claro de la actividad?**

nada, fui lento pero se entendió

**Como podríamos mejorarla?**

...

**Comment by nykka** [comment]
Hola! Te faltaría armar la lista utilizando los bloques HTML.

**Comment by marianoguerra** [comment]
aprobado!
