### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by cintialop** [CreemosEnLaRed/entregas#94]
Dirección de la actividad: https://cintialop.github.io/actividad2

**Comment by nykka** [comment]
Hola! No está subido el archivo bloques correctamente.

**Comment by cintialop** [comment]
gracias, creo que pude corregirlo

**Comment by nykka** [comment]
Aprobada la actividad! La única observación que te haría es que podrías haber usado rutas relativas en vez de absolutas para las imágenes.
