### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by leicba** [CreemosEnLaRed/entregas#96]
Dirección de la actividad: https://leicba.github.io/actividad-2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Que con los bloques html ya vamos escribiendo los códigos.

**Que no fue claro de la actividad?**
Al principio la consigna escrita me generó muchas dudas y me costaba entender, cuando vi el vídeo comprendí todo finalmente.

**Como podríamos mejorarla?**

Por lo menos en mi caso, con el video me fue genial y comprendí lo que me había dado dudas de la consigna escrita.

**Comment by nykka** [comment]
Perfecto!
