### ISSUE TITLE
Entrega de Actividad 3 - <Lei Cordoba>

### ISSUE THREAD

**Issue by leicba** [CreemosEnLaRed/entregas#97]
**IMPORTANTE** cambiar en el titulo del issue *<user Telegram>* por su user o nombre que aparece en telegram.

Dirección de la actividad: https://leicba.github.io/actividad-3/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

Que aprendi muchos tags nuevos y reforcé el cómo está compuesto un codigo, que ya lo venía viendo desde bloques con la solapa html.

**Que no fue claro de la actividad?**

Me pareció super clara.

**Como podríamos mejorarla?**
Estaría genial algun apunte o ayuda escrita sobre los tags basicos y su significado!

**Comment by marianoguerra** [comment]
perfecto! :clap:
