### ISSUE TITLE
Entrega de Actividad 2

### ISSUE THREAD

**Issue by lucianamora** [CreemosEnLaRed/entregas#98]
Dirección de la actividad: https://lucianamora.github.io/actividad2/

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...Entender un poco más del lenguaje html

**Que no fue claro de la actividad?**

...Fue bastante claro

**Como podríamos mejorarla?**

...Me gustaría mejorar a mí mi contenido pero por falta de tiempo estoy haciendo solo lo que pide la actividad

**Comment by nykka** [comment]
Hola! El ejercicio está correcto, pero fijate que las imágenes no se están mostrando.
