### ISSUE TITLE
Entrega de Actividad 3  <Luchi Carioni>

### ISSUE THREAD

**Issue by luchicarioni** [CreemosEnLaRed/entregas#99]
Dirección de la actividad:  luchicarioni.github.io/actividad-3 

Soy oyente? No

Si tenes ganas, contesta alguna o todas las preguntas: (las respuestas son publicas en internet, si preferís mandarnos feedback privado lo podes hacer por las redes sociales o a nuestro mail)

**Que te gusto de la actividad?**

...

**Que no fue claro de la actividad?**

...

**Como podríamos mejorarla?**

...

**Comment by marianoguerra** [comment]
perfecto :rocket:
